# -*- coding: utf-8 -*-
"""Gaming_solution _final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iprSpzClXhRgX3hNeyOqsfghI5y68YpV
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder,LabelEncoder

df=pd.read_csv('/content/gaming_addiction.csv')

df.head()

df.columns

df.info()

df.shape

df.describe()

df.nunique()

df['gender'].unique()

df['gender'].value_counts()



df.isnull().sum()

df.duplicated().sum()

df.drop(columns=['user_id','country','subscription_status','gender','addiction_score','addiction_severity','toxic_chat_reports','burnout_probability','income_level','churn_probability','behavioral_cluster'],inplace=True)

df.isnull().sum()

df.isnull().sum()

df['depression_indicator']=df['depression_indicator'].fillna(df['depression_indicator'].mean())
df['gpa_or_performance_score']=df['gpa_or_performance_score'].fillna(df['gpa_or_performance_score'].mean())

num=df.select_dtypes(include=['int64','float64'])
cat=df.select_dtypes(include=['object'])


for col in num.columns:
  sns.histplot(data=df,x=col,kde=True)
  plt.show()

for col in cat.columns:
  sns.countplot(data=df,x=col)
  plt.show()

for col in cat.columns:
    print(f"Column: {col} -> Unique values: {cat[col].nunique()}")
    print("-------------------")

df

corrs = df.corr(numeric_only=True)['addiction_binary'].sort_values(key=abs, ascending=False)
print(corrs)

cat

X=df.drop(columns=['addiction_binary'])
y=df['addiction_binary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

for col in cat.columns:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

X_train.shape

y_train.shape

from sklearn.preprocessing import StandardScaler

scale=StandardScaler()

X_train_scale=scale.fit_transform(X_train)
X_test_scale=scale.transform(X_test)

"""**Logistic regression**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

model_logistic=LogisticRegression()

model_logistic.fit(X_train_scale,y_train)
ypred_lo=model_logistic.predict(X_test_scale)

print(f'accuracy ={accuracy_score(y_test,ypred_lo)}')

print('accuracy of train data : ')

print(model_logistic.score(X_train_scale,y_train))

print('accuracy of test data : ')

print(model_logistic.score(X_test_scale,y_test))

print('report of random forest model')
print(classification_report(y_test,ypred_lo))

"""*Support Vectot Machine *"""

from sklearn.svm import SVC

model_Svc=SVC(kernel='rbf',C=1)

model_Svc.fit(X_train_scale,y_train)
ypred_SC=model_Svc.predict(X_test_scale)

print(accuracy_score(y_test,ypred_SC))

print('accuracy of train data : ')

print(model_Svc.score(X_train_scale,y_train))

print('accuracy of test data : ')

print(model_Svc.score(X_test_scale,y_test))

cm=confusion_matrix(y_test,ypred_SC)
print(f'confision matrix : \n{cm}')

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

print(classification_report(y_test, ypred_SC))

"""**Decision Tree **"""

from sklearn.tree import DecisionTreeClassifier, export_text

tree_overfit = DecisionTreeClassifier(random_state=42 ,max_depth=3 ,criterion='gini')

tree_overfit.fit(X_train, y_train)

y_pred=tree_overfit.predict(X_test)

print('Accuracy_score: ')
print(accuracy_score(y_test,y_pred))

print('accuracy of test data : ')
print(tree_overfit.score(X_test,y_test))
print('accuracy of train data : ')
print(tree_overfit.score(X_train,y_train))

print(classification_report(y_test, y_pred))

cm=confusion_matrix(y_test,y_pred)
print(f'confision matrix : \n{cm}')

"""**Random_forest**"""

from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=120 , max_depth=5,criterion='gini' ,random_state=42)

rf_clf.fit(X_train,y_train)

y_pred_rf=rf_clf.predict(X_test)

print(accuracy_score(y_test,y_pred_rf))

print('accuracy of test data : ')
print(rf_clf.score(X_test,y_test))
print('accuracy of train data : ')
print(rf_clf.score(X_train,y_train))

print('report of random forest model')
print(classification_report(y_test,y_pred_rf))

"""KNN

"""

from sklearn.neighbors import KNeighborsClassifier

scores = []

for k in range(1, 21):
    model_KNN = KNeighborsClassifier(n_neighbors=k)
    model_KNN.fit(X_train_scale, y_train)
    pred = model_KNN.predict(X_test_scale)
    scores.append(accuracy_score(y_test, pred))

scores

print('accuracy of test data : ')
print(model_KNN.score(X_test,y_test))
print('accuracy of train data : ')
print(model_KNN.score(X_train,y_train))

"""Ada Boast & Gride Search


"""

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV

ada = AdaBoostClassifier(random_state=42)


ada_param_grid = {
    'n_estimators': [50, 100, 150, 200],
    'learning_rate': [0.01, 0.1, 0.5, 1.0]
}


ada_grid = GridSearchCV(ada, ada_param_grid, cv=5, scoring='accuracy', n_jobs=-1)
ada_grid.fit(X_train_scale, y_train)


print("Best AdaBoost Params:", ada_grid.best_params_)
print("Best AdaBoost Accuracy:", ada_grid.best_score_)

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)

ada_model.fit(X_train_scale, y_train)

ada_pred = ada_model.predict(X_test_scale)
print("AdaBoost Accuracy:", accuracy_score(y_test, ada_pred))

"""# Neural Network"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([

    Dense(16, activation='relu', input_shape=(X_train_scale.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')

])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_scale,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

loss, accuracy = model.evaluate(X_test_scale, y_test)

print("Accuracy:", accuracy)

"""deployment

1. train model
"""

import joblib
df = pd.read_csv("gaming_addiction.csv")

DROP_COLS = [
    "user_id", "country", "subscription_status", "gender",
    "addiction_score", "addiction_severity", "toxic_chat_reports",
    "burnout_probability", "income_level", "churn_probability",
    "behavioral_cluster",
]
df = df.drop(columns=DROP_COLS)

df["depression_indicator"] = df["depression_indicator"].fillna(
    df["depression_indicator"].mean()
)
df["gpa_or_performance_score"] = df["gpa_or_performance_score"].fillna(
    df["gpa_or_performance_score"].mean()
)

X = df.drop(columns=["addiction_binary"])
y = df["addiction_binary"]

CAT_COLS = X.select_dtypes(include=["object"]).columns.tolist()
NUM_COLS = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

encoders = {}
for col in CAT_COLS:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])
    encoders[col] = le

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoders, "encoders.pkl")
joblib.dump(list(X.columns), "feature_columns.pkl")
joblib.dump(CAT_COLS, "cat_columns.pkl")
joblib.dump(NUM_COLS, "num_columns.pkl")

"""2. app"""